### PR TITLE
add option of "preferred_attr_units"

### PR DESCRIPTION
**Pull request by eteq**
As suggested by @taldcroft in #12

### CODE REVIEW

**Comment by eteq** [comment]
@taldcroft - that's a fair point - I user `iteritems` because it's more efficient for large dictionaries on py2 (because it's a generator instead of creating copies of the keys/value references), but for everywhere it's used here, that's totally unnecessary.  Will change.

**Comment by eteq** [comment]
Actually, I initially had it as degrees, then changed it to hours because I couldn't decide.  So I'll let your vote tip it back to degrees :wink:

**Comment by taldcroft** [comment]
Will the current code flow down to the case where you access an attribute individually?  I'm thinking not since it just hits the top-level repr.

```
In [22]: c = ICRS(1*u.deg, 2*u.deg)

In [23]: c
Out[23]: <ICRS Coordinate: ra=1.0 deg, dec=2.0 deg>

In [24]: c.ra
Out[24]: <Longitude 0.017453292519943098 rad>   # should be preferred unit
```

**Comment by eteq** [comment]
Good point!  Fixed in the commit I just pushed up.

**Comment by eteq** [comment]
Does this look good to you now, @taldcroft ? If so, I'll merge it.

**Comment by eteq** [comment]
I'll assume the lack of further comments here means it's fine, so I'll merge this to speed things along.  Of course feel free to comment more or open a new PR if other changes come up.

**Comment by taldcroft** [comment]
Looks good.  :clap:

**Pull request merged**
