### PR TITLE
Implementation of frames/low-level classes

### PR DESCRIPTION
**Pull request by eteq**
This PR implements the APE5 api for the low-level classes.  There are a few things that might be improved, and some deviations from the API I was forced into upon trying to implement.  All are detailed below.

At his point, all of the APE5 API is working except the high-level part.  You can check that by doing:
`python setup.py test -t astropy/coordinates/tests/test_api_ape5.py`

cc @astrofrog @taldcroft @mhvk @Cadair @adrn

Changes from API plan:
- It's not currently possible to do `ICRS(1*u.deg, 2*u.deg)` - you have to do `ICRS(ra=1*u.deg, dec=2*u.deg)`.  There's a variety of reasons for that on the implementation side... it's _possible_ but a bit awkward to get around that.  I'd say it shouldn't hold up this PR/the main PR, but could be added later.
- `frame_attr_names` is now a dict, not a list.  It maps attribute names to their default values.  It shouldn't actually affect anything too much, because iterating over it still gets the names of the attributes.  But it is slightly different from what the API implied.
- This isn't exactly a "change", but it is something not clearly discussed in the API.  Transformations that are more than one "hop" now have to make an assumption about what the intermediate frame attributes should be.  As it stands right now, they just use any attributes in the `to` frame if they overlap, and otherwise they just use defaults.  To control this better, I also added a `GenericFrame` that will allow the high-level class to set _all_ frame attributes for intermediate transformations stages. 

Improvements needed:
- The docs aren't changed at all - will need to do this before a release, but not crucial for the implementation.
- `__repr__` (and `__str__`) aren't great - I think @mhvk was going to work on this for the representations?  Perhaps with some delegation there, this can be substantially improved.  It's not crucial that it be _really_ good, because that's really the domain of the high-level class, but I think it's be nice if it's at least comparable to numpy arrays or similar.
- `__eq__`, `__len__` and such are all missing.  This isn't necessarily critical, but we probably want at least some of those.  But they're not in the representations, so we need to decide what to do about them.
- The accuracy tests need to be updated for this scheme... So there could be some accuracy issues, although I took the algorithms straight from the old implementations, so they _shouldn't_ be different (famous last words...)

### CODE REVIEW

**Comment by taldcroft** [comment]
Hmm, from the high-level perspective the plan was that low-level coordinates would handle much of the input validation and accept positional args `ICRS('1 deg', '2 deg')` per the API.  :-)  I do think that the low level classes really need to be able to do this.

I'm not sure that _really_ good representations are realistic in time for the feature freeze.  I haven't included doing anything with representations in my time estimates...

**Comment by eteq** [comment]
Hmm... As I said, that could be done without _too_ much work, but the biggest complication is this: Right now it's not clear how to decide the "intended" order.  One possibility that occurs to me now is to just use whatever the preferred representation's order is.  E.g., `SphericalRepresentation.__init__` has the order `lon,lat,distance`, and I could just say that then `ICRS` has to be `(ra, dec, distance)` to match.  That also has the advantage of being fairly trivial to imlement given the way it's done here.

And I totally understand there's not enough time to get all the string stuff in here, @taldcroft - I was thinking if we can get something that's "at least ok" now, you'll have all of the next release cycle to focus on getting it right.

By the way, if you want, I can take a crack at the code to plug `SkyCoordinates` into the transform graph once you've got the basic stuff moved over.  It _might_ be trivial with `GenericFrame`, but there might be something I missed that makes it more complex...

**Comment by mhvk** [comment]
@eteq - could you make `preferred_attr_names` an `OrderedDict`, so that the classes can indicate that way what the preferred order is? (This probably would match the order of the representation classes, but would seem more flexible and easier to implement.)

**Comment by adrn** [comment]
Just marking some territory: I'm going to have a go at updating the tests..

**Comment by astrofrog** [comment]
Just a quick note - I think it would be important to get `ICRS(1*u.deg, 2*u.deg)` to work since it will then provide backward-compatibility with existing code.

**Comment by eteq** [comment]
Good points, @astrofrog and @mhvk .  I'll have a go at this soon and try to convince it to accept ordered arguments using `OrderedDict`.

**Comment by eteq** [comment]
Alright, with the help of @adrn, I can now report the accuracy tests are all running, and more importantly, passing!

Looking at this reminds me of something quite technical that's mostly aimed at @astrofrog, though (as the implementer/fixer of the E-terms stuff for FK4):
This required me to take a closer look at the FK4 precession code while implementing the "self transforms" (e.g. FK4->FK4 with different equinoxes).  Previously, we were doing precession for FK4 directly on the FK4 system.  But if I understand correctly, that's not right, because the e-terms muck up the frame in ways that aren't just rotation.  So as of this PR, now, to do FK4 precession, it does FK4(oldeqx)->FK4NoE(oldeqx)->FK4Noe(newex)->FK4(neweqx) .  Does that seem right to you, @astrofrog ?  I don't think it's wrong, but it might be wasteful if I'm incorrect that FK4 w/e-terms is still precessible.

**Comment by eteq** [comment]
And the most recent commits now put back in positional arguments using `OrderedDict` following @astrofrg @mhvk and @taldcroft's suggestions.

**Comment by astrofrog** [comment]
@eteq - great! does this mean that the accuracy tests can be almost reverted back to be backward-compatible?

**Comment by eteq** [comment]
@astrofrog - probably not... The problem is that the old way of specifying "frames" is subtly different, so the actual implementation of the accuracy code had to change.  This doesn't matter for most use cases that just do e.g. `.tranform_to(FK5)`, but if you have an obstime or equinox, it is now relevant.  

And did you see my question about precession in FK4?  Does the new scheme make sense to you?

**Comment by taldcroft** [comment]
@eteq - had to attend to other things for a few days but I'm back on coordinates now.  I want to develop `SkyCoordinate` based off of this branch as it now stands to be able to actually test transforms and all the new stuff.  Are you planning to merge this into `coordinates-ape5` soon?  My changes are just in two files so it's trivial to rebase on whatever branch.  If you have a suggestion for the best way to proceed I'm listening.  For now I'm starting from `coordinates-ape5-frames` and will go from there.

**Comment by eteq** [comment]
@taldcroft - a bit later today I'm planning to go through and get all the coordinates tests passing on this branch (Except for the high-level one), and if no one has left more comments that need adressing by then, I'll merge it, and you can rebase on that.

One thing to be aware of: eteq/astropy#12  - that implements `__repr__` on representations.  I'm planning to change the `__repr__` on the frames to use that once both are merged.  It also adds some representation attributes you may want for implementing the high-level `__repr__` (or other string output).  So you may want to avoid working on that until that's merged in (I'll do that today/early tomorrow too unless someone else issues opinions).

**Comment by taldcroft** [comment]
Maybe I'm misunderstanding something, but I don't get why all the pre-APE5 code, in particular `builtin_systems.py` and most (all?) of `coordsystems.py` are still included and are still what you get from `coordinates/__init__.py`.  This is confusing because I want this branch to give me APE5 version of coordinates and have no trace of the pre-APE5 stuff.  I just did `from astropy.coordinates import *` for playing around until I realized this is not what I want.

In particular, maybe this is philosophical, but tests have been changed like:

```
-from ... import Galactic, FK4
+from ...builtin_frames import Galactic, FK4
```

I would argue the original form is better because that guarantees the test will use the exact `Galactic` that the user is getting from `from astropy.coordinates import Galactic`.

**Comment by eteq** [comment]
@taldcroft - That's exactly what I _wanted_ to do, but the problem is that some of the other parts of astropy use the old-style coordinates at import, so `python setup.py build` fails right now if I replace the old-style stuff.  

So the plan I was thinking was to get the internal coordinate tests working, and right before the PR to master, make the integration with the rest of astropy work.  That includes just what you were thinking, of stripping out all the old stuff, and it could also include removing `builtin_frames` and `representation` from the tests where relevant.

**Comment by taldcroft** [comment]
@eteq - Can you help me understand the new transform graph object?  I want to make this code work:

```
    @override__dir__
    def __dir__(self):
        """
        Override the builtin `dir` behavior to include:
        - Transforms available by aliases
        - Attribute / methods of the underlying self._coord object
        """

        # determine the aliases that this can be transformed to.
        dir_values = set()
        for alias in master_transform_graph.get_aliases():
            tosys = master_transform_graph.lookup_name(alias)
            if self._coord.is_transformable_to(tosys):
                dir_values.add(alias)

        # Add public attributes of self._coord
        dir_values.update(set(attr for attr in dir(self._coord) if not attr.startswith('_')))

        return dir_values
```

The problem is that using `baseframe.frame_transform_graph` I get:

```
In [19]: from astropy.coordinates.baseframe import frame_transform_graph

In [20]: frame_transform_graph.get_aliases()
Out[20]: []
```

**Comment by taldcroft** [comment]
(BTW, obviously the `dir` function is not of primary importance, but if that works I can make other stuff work).

**Comment by taldcroft** [comment]
@eteq - About the integration strategy, I guess that makes sense.  Is getting the build to work something that requires pervasive changes?  For now I just stubbed my `__init__.py`

```
--- a/astropy/coordinates/__init__.py
+++ b/astropy/coordinates/__init__.py
@@ -10,10 +10,10 @@ from __future__ import (absolute_import, division, print_function,

 from .errors import *
 from .angles import *
-from .coordsystems import *
+from .baseframe import *
 from .distances import *
 from .transformations import *
-from .builtin_systems import *
+from .builtin_frames import *
 from .name_resolve import *
 from .matching import *
```

**Comment by eteq** [comment]
@taldcroft - Hmm, the bit with the aliases is probably a bug.  What you're doing with `dir` is exactly what was intended, but apparently something's not correctly populating the list of aliases.  I'll look into that and get back to you.

(Also, if you're working on it right now, you might try sending me a google+ message - might be faster)

As for the integration, when I made the changes you just described, `python setup.py build` starts throwing errors in `vo`.  I don't think any of it is major, it's just a matter of fixing some of the places where coordinates are defined to no longer use `units` keywords.

**Comment by taldcroft** [comment]
Is this relevant to the transform graph issue?

```
In [1]: import astropy.coordinates
WARNING: AstropyDeprecationWarning: 
        Use BaseCoordinateFrame.short_name instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use BaseCoordinateFrame.short_name instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use BaseCoordinateFrame.short_name instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use BaseCoordinateFrame.short_name instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use BaseCoordinateFrame.short_name instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use BaseCoordinateFrame.short_name instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.static_transform_matrix instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.dynamic_transform_matrix instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.transform_function instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.transform_function instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.dynamic_transform_matrix instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.dynamic_transform_matrix instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.dynamic_transform_matrix instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.dynamic_transform_matrix instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.dynamic_transform_matrix instead. [astropy.coordinates.builtin_systems]
WARNING: AstropyDeprecationWarning: 
        Use TransformGraph.dynamic_transform_matrix instead. [astropy.coordinates.builtin_systems]
```

**Comment by taldcroft** [comment]
Oh wait, I just noticed the above is in `builtin_systems` so it should not be relevant.

**Comment by eteq** [comment]
@taldcroft - no, that's because I put a deprecation marker on the old-style graph decorators.  Those will disappear when `builtin_systems` does.

**Comment by eteq** [comment]
Alright, the tests are now all passing (except for the high-level class APE5 test and the doctests, which we will address later).  So I will merge this into `coordinates-ape5` to make it easier to work from there.  But of course, feel free to comment here or issue PRs against that branch (especially if you disagree with my interpretation of FK4, @astrofrog)

**Comment by taldcroft** [comment]
I wanted to open an issue on the @eteq fork but that doesn't seem possible.  Anyway, the default repr still needs some work:

```
In [3]: c = FK4(1 * u.deg, 2 * u.deg)

In [4]: c
Out[4]: <FK4 Coordinate: equinox=B1950.000, obstime=B1950.000, ra=1.0 deg, dec=2.0 deg>

In [5]: c.transform_to(FK5)
Out[5]: <FK5 Coordinate: equinox=J2000.000, ra=0.0286395484797 rad, dec=0.0397644748615 rad>
```

**Comment by taldcroft** [comment]
Another issue (perhaps premature since development is on-going, but stated for the record).

No input validation and `obstime` is settable. 

```
In [22]: c = FK4(1 * u.deg, 2 * u.deg, equinox=2)

In [23]: c.obstime = 'hello world'
```

About `obstime` being settable, there is an explicit setter function there, so is this on purpose?

**Comment by eteq** [comment]
@taldcroft - the issues are normally off in my repo so as to prevent confusion with other astropy repos, but you're right it makes sense right now...

Re repr:  What are you saying is the problem?  It seems to be working just how it's supposed to... Do you mean the fact that it converts to radians?  That's intended: it's deferring to the representation repr, which gets units from the representation object.  We don't want the _low-level_ objects to magically hide the `Quantity` type, after all.  The idea was that the high-level class does all the fancier stateful string formatting, and the low-level `repr`s are mainly convenience devices. But if there's a reason to put some of the pre-steps in the lower-level classes as methods, that's fine too.

`obstime` is an oversight,  it shouldn't be settable - will fix.  As for input validation, I guess I hadn't thought that hard about the right place to validate, but I guess it does make sense to add it to the various `__init__`s.

**Comment by taldcroft** [comment]
@eteq - I see your point about not making assumptions or keeping stateful information, but I wonder if the current frames isn't taking that too far.  I had always thought of `SkyCoord` as being a convenience wrapper that does maintain state and makes a smoother experience, but not that it would be the _only_ useful way for astronomers to work with coordinates.  In essence, if doing a simple transform like ICRS => FK5 always converts the lon / lat units to radians, then the low-level classes will be pretty inconvenient to work with.  I suspect if the API take-2 document highlighted this feature that there would have been some pushback.  It will also introduce more breakage in existing code / analysis workflows.

I haven't looked at the code, but it seems like at the end of the transform chain in the `transform_to()` method there shouldn't be a problem setting the output units to be the same as the input units.  That is not doing anything magical, instead that is doing what users normally expect from a unit-ful analysis.

Having said this, is there a sanctioned way to change the units for lon / lat components in a coordinate object?

**Comment by eteq** [comment]
@taldcroft - The intent here is to help get people into the mindset of using `Quantity` and similar idioms.  That is, they only need worry about the units _or_ the representation type at input/output, and let `Quantity` and the transformations convert as needed in-between. I'm not terribly concerned about breaking existing code in this way, because the _existing_ transformations don't always maintain units, either. 

Besides making things simpler, this is important practically for optimization: there's a lot of inefficiency if you have to transform back and forth from spherical <-> cartesian every step, so if you look closely you'll see that if you do `cicrs.transform_to(FK5)`, the resulting object's `data` is actually *cartesian`, not spherical.  The spherical representation is only created on-demand if you do`repr`.

So it's quite non-trivial to actually _force_ the `data` to be the same representation and units you started with.  And for some transformations coming up, it wouldn't be at all natural  (e.g., AltAz <-> ITRS, which is on a cartesian-defined geoid). So the idea is to tell users they should do `coord.ra.to(u.deg)` if they really explicitly need a particular unit `Quantity` (or, for an array, the shorthand `coord.ra.deg`). 

_But_ I do see your point that this makes  `repr` harder to use.  It would be a trivial change to make the low-level classes have a "preferred_unit" that shows up in `repr`, and it could also be used in usage like `c.ra`, where a conversion was already necessary anyway.  The question is just if that is _more_ confusing because it's different from the underlying `data`?  Let me know what you think, @taldcroft, and if that seems like a good solution I can implement it pretty easily.

**Comment by mhvk** [comment]
@taldcroft - I was about to make the same point as @eteq, that really one should worry only about the representation in `repr` and `str`, not what it is internally -- let `Quantity` take care of that!

That said, it would not be difficult to keep the angular unit even at the lowest level, by having the representation classes have both a `unit` (which should be that of the distance, or whatever) and an `angular_unit`. For the `CartesianRepresentation`, the latter might stay at some default upon direct initialization, but it could get set when it is created from, e.g., a `SphericalRepresentation`.

**Comment by taldcroft** [comment]
Agreed that the question is about the repr of `data` visible to the user.  The actual `data` units or even coordinate representation (i.e. spherical or cartesian) doesn't matter and I rescind suggestion of actually modifying that.  But the unit of attributes that are user-facing is important.  I would certainly be happy with a `preferred_unit` or `angular_unit` attribute which makes coordinate angles show up in degrees by default.

**Comment by eteq** [comment]
Alright, I will implement something along the line of `preferred_unit` tomorrow, @taldcroft .

**Pull request merged**
