### PR TITLE
SkyCoord to_string method

### PR DESCRIPTION
**Pull request by taldcroft**

### CODE REVIEW

**Comment by eteq** [comment]
This is great except for one thing I don't think it lets me do (which is important): "HH:MM:SS.S +DD:MM:SS.S".  I can get very close with `.to_string('hmsdms',sep=':',alwayssign=True)`, but then alwayssign is on the hours, too.  

Maybe just add a style "hms+dms"? Or just change the "hmsdms" style to have alwayssign the default for the lat string?

**Comment by taldcroft** [comment]
@eteq - check out 6511830.  This changes the default of `hmsdms` as you suggested but goes a little further to also include `pad=True`.  I think in general HMS coords look nicer and more consistent with padding.  BUT, if you don't like that, there is the important change bundled here which is making the user kwargs have precedence over the style defaults.  I think this makes more sense and gives more configurability.  It _does_ mean you can do something stupid like `to_string('decimal', decimal=False)`, but whatever.

**Comment by eteq** [comment]
Looks good now, @taldcroft, except apparently it needs a rebase...

**Comment by taldcroft** [comment]
OK rebased.

I see you took out the API test section in `test_sky_coords.py`.  That's fine, but that version fixed a number of things that will be failing in `test_api_ape5.py` like needing `allclose` or using the wrong unicode symbols.

**Comment by eteq** [comment]
@taldcroft - what I actually did was copied-and-pasted your test over into `test_api_ape5` with a few modifications to make it work in that context.  Did I leave something out?

**Comment by eteq** [comment]
At any rate, merging!

**Comment by taldcroft** [comment]
Sorry, must've been a stale version of `test_api_ape5` I was looking at.  I see now that it looks like what I expect.

**Pull request merged**
