### PR TITLE
Coordinates ape5 rep tests

### PR DESCRIPTION
**Pull request by eteq**
@astrofrog @Cadair - this fixes up the APE5 api test to work with the representations code.  It's mostly relatively minor things, but there's one issue as yet un-resolved: why doesn't:

```
cr = CartesianRepresentation(x=randn(100)*u.kpc,y=randn(100)*u.kpc,z=randn(100)*u.kpc)
cr.x.kpc
```

work?  Shouldn't `cr.x` be a `Distance` if it has length units?

### CODE REVIEW

**Comment by astrofrog** [comment]
@eteq - I didn't think that cartesian coordinates were distances as such (they are lengths). The distance class only allows positive values by default and it didn't seem natural to use the class for the cartesian coordinates. But we can certainly change it.

**Comment by eteq** [comment]
@astrofrog - Ahhh, right, I forgot that it's positive-only.  Just pushed up a commit that adjusts that test appropriately.  Do the other changes seem right to you?

**Comment by eteq** [comment]
To clarify, with that last commit, `python setup.py test -t astropy/coordinates/tests/test_api_ape5.py --args="-k representations"` now passes

**Comment by eteq** [comment]
Oh, and @astrofrog and @Cadair : I changed `PhysicsSphericalRepresentation` to use `r` instead of `distance`, as the API specified.  Was that an intentional change on your part, or just an oversight?

**Comment by eteq** [comment]
I'm going to go ahead and merge this to make things easier for the frames work, @astrofrog and @Cadair, because we need the APE5 API tests to pass.  But if you want to change any of this, feel free to PR.

**Comment by astrofrog** [comment]
Seems fine to me!

**Pull request merged**
