### PR TITLE
High-level SkyCoordinate class (WIP)

### PR DESCRIPTION
**Pull request by taldcroft**
After a long journey this PR is finally based on the right branch.

### CODE REVIEW

**Comment by taldcroft** [comment]
Quick question about API.  Do we want to support flexibility and a certain amount of inference for the positional args?  It can quickly get complicated, but I'm worried that the minimal way to make an ICRS coordinate now has become verbose again.

```
c = ICRS('01h02m03d', '2d4m2s')  # Pre APE5
c = SkyCoordinate('01h02m03d', '2d4m2s', system='icrs')  # Post APE5
```

Options:
- Args that look like a system name are treated as such
- Default `system` to 'icrs'.  Right now it defaults to None, which is just crippled `icrs` in that you cannot transform to anything else.
- Something with length units is treated as distance.

**Comment by taldcroft** [comment]
I meant to cc: @astrofrog since he was one of original drivers for a more compact API.

**Comment by eteq** [comment]
@taldcroft - I like your option 1 and 3.  That changes the minimal example to:

```
c = ICRS('01h02m03d', '2d4m2s')  # Pre APE5
c = SkyCoordinate('01h02m03d', '2d4m2s', 'icrs')  # Post APE5
```

which seems better to me.  If number of characters is the worry, one option might by to do `SkyCoord` instead of `SkyCoordinate` - I think "Coord" on its own is too ambiguous, but "SkyCoord" is just fine.

I am -1 on 2, though.  I like your current "crippled ICRS" because that means it forces the user to think about what they mean if they do anything that requires transformation - that is, we don't want people assuming it's FK5 when it's actually defaulting to ICRS.  There are some sub-fields where "default=FK5" makes sense, and therefore those users might assume that. After all, "In the face of ambiguity, refuse the temptation to guess."...

An addition that makes it a bit better: make it possible to _add_ a proper system to the "None" system, like so:

```
>>> c1 = SkyCoordinates('01h02m03d', '2d4m2s')
>>> c3 = c1.transform_to(FK5)
... whoops, an error! 
>>> c2 = SkyCoordinates(c1, 'icrs')
>>> c3 = c1.transform_to(FK5)
```

That way even If I'm doing the quick-and-dirty initial approach, I can add a system later when I realize what I actually meant to do.

**Comment by eteq** [comment]
FYI, @taldcroft - I just pushed up some changes to coordinates-ape5 that fix it so that the coordinate aliases are now working.  They're currently all just lower-case versions of the class names.  I also merged #13, and soon will update the lower-level frames to use that for `__repr__`, so you might find that helpful here as well.

**Comment by taldcroft** [comment]
Question.  What happens for:

```
>>> c3 = c1.transform_to(FK5)
>>> c4 = SkyCoord(c3, 'fk4')  # Does it propagate the existing equinox or use FK4 default
```

More importantly, I think the current SkyCoord may be doing the wrong thing for a coordinate input because it just grabs the longitude and latitude components and initializes a new FK4 coordinate, while you might expect that `SkyCoord(c3, 'fk4')` is doing a `transform_to(FK4(equinox, obstime))` (roughly speaking).

**Comment by taldcroft** [comment]
Likewise, does this _set_ the equinox or _precess_ the equinox?

```
>>> c2 = SkyCoord(c1, equinox='J1975.0')
```

**Comment by taldcroft** [comment]
Thinking about this more, it's easier in the code, and more importantly easier (I think) to provide users with a consistent story of how things work, if we choose the **set** option.  In other words whenever you initialize a new coordinate from an existing coordinate and modify any attributes like system or equinox etc, it just takes the existing coordinate values (lon, lat, distance) and makes a new coordinate with the new equinox, system, obstime etc.

Otherwise there might even be some ambiguity about the order of operations, do you precess first and then transform system, or the other way around?

**Comment by eteq** [comment]
@taldcroft - Yeah, I agree set is the better option for just the reasons you said.

And actually, that makes me think of a slightly more intense (but less ambiguous) version: Only allow setting of attributes that are not _already_ set.  So something like this:

```
>>> c1 = SkyCoord('01h02m03d', '2d4m2s')
>>> c2 = SkyCoord(c1,system='icrs')
>>> c3 = SkyCoord(c2, obstime=Time('J1975'))  # obstime will be used only if you convert to FK4 or whatever
>>> c4 = SkyCoord(c2, system='fk4')
ValueError: `system` already set - use `transform_to` to convert coordinate to a new system
>>> c4 = SkyCoord(c3, obstime=Time('J1970'))
ValueError: Attribute `obstime` already set - use "overwrite=True" if you really want to do this
```

That way, there's still the option of doing this, but it catches the user who assumes e.g. `SkyCoord(c2, system='fk4')` means "do the transofmration"

**Comment by eteq** [comment]
This also made me think of something else: @taldcroft, what are you thinking is the way to handle "self-to-self" transformations?  E.g. FK5(equinox=J2000)-> FK5(equinox=J1975) ? The natural way given the low-level classes is allowing `skycoord.transform_to(FK5(equinox=Time('J1975')))`... But that's slightly different from the `SkyCoord` idiom of storing everything at the beginning.  Or should there be something like `skycoord.self_transform(equinox=Tim('J1975'))`, which either does the transform if the low-level class actually has the transform or just updates the attribute if not?

**Comment by taldcroft** [comment]
I like your "more intense" version above with _setting_ as the behavior, and will try to implement something on those lines.

On the second question of self-to-self transformations...  This raises a good question about the idiom of storing values up front.  One way to approach this is to delegate frame attributes to the internal coordinate frame object `self._coord`.  In other words if you ask for an attribute and that is a valid attribute for that frame, then return `getattr(self._coord, attr)`.  Otherwise return the relevant `SkyCoord` attribute.  The point is to never allow there to be a disconnect between what's happening in the `self._coord` frame and the SkyCoord `self`.  I haven't thought all the way through the implementation, but it should be possible to get this going in a clean way.

I was thinking about `SkyCoord.transform_to` method like in your example which basically wraps the frame version but manages the attributes appropriately.  This brings up a question though.  Let's say you have a `SkyCoord` FK5 object with equinox and obstime set.   Then the user does exactly your example `skycoord.transform_to(FK4(equinox=Time('J1975')))`.  That `FK4` frame object will have the default `obstime` (the `equinox` if I understand correctly).  `SkyCoord` would need to override the frame `obstime` with its own version.  Can you change the `obstime` or `equinox` attribute for a frame with no coordinates?

For the particular example of changing equinox, I was assuming that `SkyCoord` would delegate to the frame `precess_to` method so the user would do `c2 = c.precess_to('J1975.0')`.  [BTW, I'm also planning on taking the "anything that will initialize a Time object" strategy for inputs, where sensible].

**Comment by taldcroft** [comment]
Somewhat OT from this PR, but I noticed that the FK4 initializer still sets `obstime` to `equinox` if `obstime` is not supplied.  Isn't that pretty much always wrong?  I would have thought that `obstime` would be a required input for `FK4`.  Having the default for `equinox` is sensible however.

**Comment by eteq** [comment]
I like your idea here about keeping `self` and `self._coord` as close as possible, although see my comment below about `GenericFrame`. On you first question (about changing frame attributes w/o data): Frame objects are by design immutable, whether or not they have data - that's after all what uniquely defines the frame.  But there's certainly nothing to prevent creating a new one mixing and matching attributes as needed, and then actually using that as the new `_coord` in the new-returned `SkyCoord`.

There's a more important subtlety that may make this irrelevant, though: the _intermediate_  steps in a transform. In `SkyCoord`, you need a way to tell those intermediate steps to use attributes that may _only_ be in intermediate systems.  An example might illustrate this better: the Galactic->ICRS transform.  neither `Galactic` nor `ICRS` have an equinox.  But FK5_does_ have an equinox.  So if you have `SkyCoord(...,system='galactic',equinox='J1975').transformt_to(ICRS)`, the transformation should be actually _different_ from `SkyCoord(...,system='galactic',equinox='J2000').transformt_to(ICRS)` in the intermediate steps through FK5, even though neither the initial nor final have an equinox. 

This is why I added the `GenericFrame`: you can give it _any_ attributes and it will treat them as frame attributes.  The intended use is that you give it _all_ of the attributes the `SkyCoord` is holding.  Then,  you can do something like this inside `SkyCoord.transform_to`: `frame_transform_graph.get_transform(fromsys, tosys)(self, <generic frame object here>)`.  Then any `CompositeTransform` will use attributes from the `GenericFrame` if it needs them, but ignore them if it doesn't.  So then there's no need to worry about messing with the frame _input_ to `SkyCoord.transform_to` - rather, you construct a suitable `GenericFrame` (possibly using the input object's attributes) and use that to actually do the transform.  Does that make sense, @taldcroft ?  

Alternatively, some of this logic could be move to the low-level `transform_to` as optional additional keywords - I have no strong opinion on where the divide belongs. Or, if you prefer, I can issue a PR against your branch implementing what I'm suggesting above.

**Comment by eteq** [comment]
Oh, and one other change to note, @taldcroft : I updated the `BaseCoordinateFrame.__repr__` to better match the representations, and hopefully you can at least in part re-use that (or just use it as a guide to ~match)

**Comment by taldcroft** [comment]
@eteq - what you said doesn't entirely make sense to me.  Even if intermediate frames have extra attributes, this _must_ not make a difference in the overall transformation.  In other words the Galactic to ICRS transformation must be independent of the path, where "path" might be equinox=1975 or equinox=2000 in the intermediate FK5.

To put another way, the fundamental process here is changing the numerical representation of a physical point on the sky (e.g. from galactic frame to ICRS frame), so regardless of the different frames used in the process you have to end up with the same final output.

This does bring up a point of default values for frame attributes.  I was saying earlier that having a default for `obstime` in FK4 is wrong, but if FK4 were ever used as an intermediate frame then you would indeed need some default (or else make the transformation code fill in some arbitrary value for that intermediate frame).  In practice I don't think that happens.

**Comment by taldcroft** [comment]
About the implementation of `transform_to()` in `SkyCoord`, I don't follow why it can't delegate to the low-level classes in exactly the same way that users would:

```
c_gal = Galactic(l, b)
c_icrs = c_gal.transform_to(ICRS)
c_fk4 = c_icrs.transform_to(FK4(equinox=equinox, obstime=obstime))
```

Both of the transform examples presumably involved a "nuisance" `equinox` parameter in the intermediate transform(s), but the answer should be correct.

Hopefully I'm not having some deeper misunderstanding here...

**Comment by eteq** [comment]
@taldcroft - re: intermediate transforms: you're right that those transforms _should_ yield the same results, which is the only reason why low-level classes make sense at all.  But even in the frames we have, there are slight numerical differences, and for upcoming transforms to `AltAz`, it may materially matter for some of the atmospheric effects.  Basically, I think it will be confusing if the to/from systems obey the attributes, but _none_ of the intermediate steps do. There _has_ to be some choice of the intermediate attributes, after all, so it might as well respect `SkyCoord`, if that's available.

And just as you said, that's why I'm thinking default values are necessary - to construct intermediate frames.  There is already a case where this is true: the ICRS->Galactic transform.  The route is ICRS->FK5->Galactic, and FK5 has `equinox`, while the other two don't.  So there has to be a default `equinox`.  Even moreso for the other version of the transform, where Galactic is defined relative to FK4 (which is actually the only "offcial" one - the FK5 route is derived from that).  Then the transform is ICRS->FK4NoE->FK4->Galactic, and of course then the intermediate frames need `equinox` _and_ `obstime`.

**Comment by eteq** [comment]
Oh, and that mostly addresses your second comment: what you have there indeed "should" be correct, but there are some subtleties that might make it not quite the same, in a way that seems unintutive, at least to me.

All that said, I see your point that your solution is _much_ easier to implement quickly.  So if you want to just do that now, we can think about changing it to what I'm saying later.

**Comment by taldcroft** [comment]
> All that said, I see your point that your solution is much easier to implement quickly. So if you want to just do that now, we can think about changing it to what I'm saying later.

Ultimately I would argue we need the following (pseudocode) tests to pass for any `ra`, `dec`, `obstime` and `location`:

```
c_icrs = ICRS(ra, dec)
c_altaz = c_icrs.transform_to(AltAz(obstime, location))
sky_icrs = SkyCoord(ra, dec, obstime, location)
sky_altaz = sky_icrs.altaz  
assert c_altaz == sky_altaz
```

This should be true for any of the supported systems, and implies that there should be one unique `transform_to` method that is actually doing the work.  If there is a public low-level API and a high-level API that give different answers for the same transformation then we are going to have unhappy users.  In fact they should produce _precisely_ the same result.

I certainly did not previously appreciate the subtleties you are bringing up regarding the intermediate frame attributes.  Seems like a good argument for having all the frame classes maintain all the attributes.  :smile:

**Comment by eteq** [comment]
Well, in _most_ cases, they will give the same answer, and possibly all (I'm not _sure_ that any of the numerical effects will be important when we start using ERFA algorithms to do some of the heave-lifting).  But I disagree that `transform_to` must always do the same for the high-level class as for the low-level.  If it did, there'd be no need for the high-level class _at all_.The high-level class one holds stateful information that the low-,level does not, so they _can't_ be doing the same thing.  Instead, the thing you can trust work is this:

```
c_icrs = ICRS(ra, dec)
c_intermed1 = c_icrs.transform_to(IntermediateSystem1(obstime))
c_intermed2 = c_intermed1 .transform_to(IntermediateSystem2(location))
c_altaz = c_intermed2 .transform_to(AltAz(obstime, location))
sky_icrs = SkyCoord(ra, dec, obstime, location)
sky_altaz = sky_icrs.altaz  
assert c_altaz == sky_altaz
```

_that_ I agree should always work (assuming that's the complete set of intermediate systems).

The basic problem here is that this sort of transformations are just sometimes intrinsically complicated.  So at least in my head, the low-level/high-level separation can be thought of as "works fine without too much thought most of the time" (high-level), and "I need explicit, specific control, either due to precision needs or to write my own transforms" (low-level).  While it's still _possible_ in that cheme to have the low-level classes carry all the attributes, it makes defining transformations both more complex (and hence error-prone and harder for users) and makes them harder to optimize (which is a secondary concern, but only just).  This is effectively what's in the current system, and that was a major motivation for APE5 in the first place: separation of concerns.

**Comment by taldcroft** [comment]
@eteq - I thought the motivation for the high level class was:
- One class to initialize a coordinate in any system.
- Ability to round-trip to/from other systems without loss of attributes on the journey.

I had certainly assumed that from the high-level code perspective the transforms were a working black box and that only the final frame attributes required.  Can you write some code or at least code outline that shows how to do transforms in the high-level code with attributes available?  You said some stuff previously about generic frames etc but I honestly didn't understand that.

Even in transformation from the high-level class there is a strong possibility of going through intermediate frames without the necessary attributes having been provided by the user (ICRS => Galactic being the canonical example).  If the results are dependent on that intermediate equinox, should we issue warnings if it isn't defined?  That will generally be annoying to users, however...

What do other coordinate codes do about this fundamental issue of missing information?  Are there any other reliable packages that implement composite transforms and have addressed this issue?

**Comment by eteq** [comment]
@taldcroft - Right, I agree that's the motivation (+"a convinient place to put convenience methods like catalog matching").  I was talking about your second bullet point, and how I think it's just intrinsically incompatible with keeping _exactly_ the same transformation scheme as the low-level classes automatically.

I had also initially assumed the same as you: that the only thing that mattered were the initial and final frames.  And I think that is _almost_ true, in all cases we have right now, where the choice of intermediate attribute only affects the answer through machine precision rounding errors.  But future transforms (particularly _user_ transforms) can't guarantee that.  But we don't want that to mean that you are required to specify every conceivable intermediate frame attribute just to initialize an ICRS object. So we are then _forced_ into the situation of having to decide when to let the user provide intermediate information, and when to just use defaults.  For the low-level classes, this is a non-issue, because they never provide information beyond their own frame, to make defining transforms simpler.  But for the high-level classes we have extra frame information, so there are two options for what to do:
1. Use any frame attributes that are in the high-level class for the intermediate steps
2. Ignore the intermediate frame attributes for everything except the starting and final frame.

I think # 1 is better, because that just seems more like what I would expect.  But I'm willing to believe that # 2 might also make sense. 

As for what other codes do, I _think_ the answer is that they don't deal with this at all, because they aren't as flexible. The codes I can think of don't allow users to write their own coordinate systems/transformations, so they don't worry about these generic questions.  They just make sure that it makes sense for their particular supported coordinate frames.  The most general one I know of in this respect (and the one that inspired our Frames scheme) is AST - what they do is store all the possible frame attributes that their supported systems use (e.g., they have effectively _only_ high-level coordinates), so they just use those attributes as the intermediate ones.  But there's no documented way that I can see for a user to add new attributes, so they don't have to worry about some of them being "missing".

I will issue a PR against your branch shortly on to illustrate # 1, and how it can be done with `GenericFrame`, and that might help clear some of this up?

**Comment by eteq** [comment]
I started working on the branch right now, @taldcroft, but got hung up on a couple things I'm not understanding about your implementation before I can move on:
- Why are `'system', 'equinox', 'obstime', 'location'` hard-coded?  User-defined (and future astropy-defined) frames may well need other types of attributes beyond those, so how are they supposed to add them in?
- Are `FRAME_NAMES` and the other constants at the top of the module temporary?  Because they are all populated on import, if a user adds a new class or transform, it won't be recognized by any of the `SkyCoord` machinery.  The intent with the `frame_transform_graph` is for that to all by generated on demand, rather than just once at import.  That's why `TransformGraph` has a bunch of methods to make that sort of dynamic stuff easier.
- (minor, possibly ignorable): you're using `system` to indicate things like "ICRS" and "FK5".  You're probably doing this because that's what's in APE5... But after thinking about it a bit, I think it might be easier to understand if that's instead called "frame".  See the text of APE5 for the details of this point, but the basic idea is that "coordinate system" is an overloaded word with ambiguous meaning, while "coordinate frame" is less so.

**Comment by taldcroft** [comment]
@eteq - good points.

The hardcoding and static conveniences like `FRAME_NAMES` are quasi-temporary.  Basically I don't have a good understanding of the transform graph machinery, and I just want something working now in order to have a platform from which to develop most of the code.

The convenience dicts like `FRAME_NAMES` represent my vague "high-level" interface to the transforms in a way I can understand (to avoid repeated calls to `get_aliases` and `lookup_name` etc).  It would probably be easy enough to replace those with functions or maybe a dict subclass that dynamically returns the corresponding values.  Or maybe I just need to be educated on the "right" way to use the transform graph technology.

I've actually been bothered by `system` and the way it makes the code confusing.  I'll change to `frame`.

**Comment by taldcroft** [comment]
BTW, by quasi-temporary I mean that the highest priority now is to get a fully working system that supports all the built-in frames.  We could release 0.4 with the known limitation that `SkyCoord` doesn't yet support user coordinate frames.  It's probably easy enough to make things right, but it involves more testing etc.  Feature freeze was technically a few days ago and there is still plenty to do.

**Comment by taldcroft** [comment]
Sweet, I just rebased off the latest coordinates-ape5 with the time validation stuff and this allowed a test to start passing!  Hopefully it doesn't drive anyone crazy that I'm rebasing very frequently.

**Comment by eteq** [comment]
Your last commit message makes me think of http://xkcd.com/1296/

**Comment by taldcroft** [comment]
Doo'h , cannot include backticks in commit messages.  e50348a was supposed to be

```
Change `system` to `frame` everywhere
```

This update is a really good thing since there was this continual clash between what I meant (`frame`) and what I was writing (`system`).

**Comment by eteq** [comment]
Hah, I prefer to think it was intended ;)

Re: feature freeze... That's technically today, but I think it'll have  to slip a bit (I hope no more than the end of this week) because the other members of the coordination committee have been traveling and we haven't been able to finalize the details of the feature feeze (APE2 was explicit about a +/- 1 week or so rule), and it wouldn't be fair to trigger it without warning...  But the release deadline will still happen.

I'm a bit lerry about the prospect of a `SkyCoord` that doesn't support user frames, but I agree that's better than no `SkyCoord` at all...

**Comment by eteq** [comment]
Do you want me to go through the usage of the `FRAME_NAMES` et al. and see if I can show how to use the `TransformGraph` to do it dynamically?  After all, the `TransformGraph` is designed to make exactly this process easier, but I understand it takes some learning, and I have it all in my head already...

**Comment by eteq** [comment]
I'm going to have to head out for a while now, @taldcroft, but if you do want me to go through and see where the `TransformGraph` machinery will make your life easier, just let me know and I'll do so when I get a chance.

**Comment by eteq** [comment]
@taldcroft - where are we on this?  Do you want me to do anything now?

**Comment by taldcroft** [comment]
I'm continuing work on this, slowly but surely.  If you have time then writing tests that you think should pass would help.  I'll copy here a chat question I just sent you:

I'm wondering if the ICRS frame has to have an equinox property.  It's messing things up because 'equinox' is not listed as a frame attribute for that frame, even though `equinox` is formally an reserved frame attribute name.

**Comment by taldcroft** [comment]
Controlling the interplay of possible args / kwargs supplied by user, vs. existing in a SkyCoord or frame object, default or not default, has slowed me up a bit but I think it's under control.  I've started writing some tests, but if you also thought about this and wrote tests with what you think is the expected behavior that would be a big help (and make sure I'm not diverging).

**Comment by taldcroft** [comment]
I just pushed up something with a test that fails because of the equinox issue because it thinks the ICRS coordinate already has an explicit user-specified equinox.

**Comment by eteq** [comment]
@taldcroft - note that the APE5 API for the high-level classes is in `test_api_ape5.py` - I see you have a second one in `test_sky_coord`, but I'm not sure if you copied that from the API document vs. `test_api_ape5.py`.  In any case, eventually `test_api_ape5.py` will need to work (or at least any deviations accounted for).

**Comment by taldcroft** [comment]
@eteq - copy that on APE5 testing.

Question on process.  If I merge your updates to `coordinates-ape5` into my branch instead of rebasing, will that go smoothly and let you keep a stable version of `coordinates-ape5-sky` around?  I have just seen so many problems with merging vs. rebasing that I have been avoiding merge.

**Comment by eteq** [comment]
@taldcroft - I'm not entirely sure.  I almost always rebase in situations like this, but merging _might_ work too.  You can make a "backup" copy (e.g. create a new branch pointing to the current `coordinates-ape5-sky`) and try merging and pushing that up.  You'll know if it works by whether or not github shows some of my commits in this PR.

**Comment by taldcroft** [comment]
@eteq - the next thing I need to do is make `transform_to` work as you illustrated in your PR to my branch.  Hopefully tonight, then this branch should be ready for initial testing.

Should I try to avoid modifying the `test_api_ape5.py` at all?  There is at least one mistake there, namely the unicode coordinate input is not using the correct unicode chars for minutes and seconds, and so the example there doesn't work in `Angle`.

**Comment by eteq** [comment]
@taldcroft - definitely modify `test_api_ape5.py` to reflect corrections like that.  Also, of course `SkyCoordinate`->`SkyCoord`, and the `repr` result given in the APE5 API can change to make it more consistent with what the low-level classes are doing.  Basically anything we've realized has to change can be.

**Comment by taldcroft** [comment]
@eteq - I need some help here.  I tried in 039d815 to get transforms working using `GenericFrame` and ran into a problem beyond what I can figure out.  There was one minor issue in `GenericFrame` related to how the specified frame attributes were set (need to use the super setattr I think?).  I got:

```
In [1]: from astropy.coordinates import *
^P
In [2]: sc = SkyCoord('icrs', 1, 2, unit='deg', equinox='J1999', obstime='J2001')

In [3]: sc.transform_to('fk5')
ERROR: AttributeError: 'GenericFrame' object has no attribute '_precession_matrix' [astropy.coordinates.builtin_frames]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-5b8ebb231ea2> in <module>()
----> 1 sc.transform_to('fk5')

/Users/aldcroft/git/astropy/astropy/coordinates/sky_coordinate.pyc in transform_to(self, frame)
    195 
    196         generic_frame = GenericFrame(frame_kwargs)
--> 197         newcoord = trans(self._coord, generic_frame)
    198 
    199         return SkyCoord(newcoord, frame=frame_cls)

/Users/aldcroft/git/astropy/astropy/coordinates/transformations.pyc in __call__(self, fromcoord, toframe)
    839         xyz = fromcoord.represent_as(CartesianRepresentation).xyz
    840         v = xyz.reshape((3, xyz.size // 3))
--> 841         v2 = np.dot(np.asarray(self.matrix_func(fromcoord, toframe)), v)
    842         subshape = xyz.shape[1:]
    843         x = v2[0].reshape(subshape)

/Users/aldcroft/git/astropy/astropy/coordinates/builtin_frames.pyc in icrs_to_fk5(icrscoord, fk5frame)
    335 def icrs_to_fk5(icrscoord, fk5frame):
    336     # ICRS is by design very close to J2000 equinox
--> 337     pmat = fk5frame._precession_matrix(_EQUINOX_J2000, fk5frame.equinox)
    338     return pmat * icrscoord._ICRS_TO_FK5_J2000_MAT
    339 

AttributeError: 'GenericFrame' object has no attribute '_precession_matrix'
```

**Comment by taldcroft** [comment]
BTW you should be able to debug or say what I'm doing wrong outside the context of my branch since this issue is (I think) reproducible just in lines 196 and 197.

```
In [14]: from astropy.coordinates import *
In [15]: import astropy.units as u
In [16]: gf = GenericFrame({})
In [17]: c = ICRS(1*u.deg, 2*u.deg)
In [18]: fk5 = FK5()
In [19]: trans = frame_transform_graph.get_transform(c.__class__, fk5.__class__)
In [20]: trans(c, gf)
ERROR: AttributeError: 'GenericFrame' object has no attribute '_precession_matrix' [astropy.coordinates.builtin_frames]
```

**Comment by eteq** [comment]
@taldcroft - it looks to me like you're using it correctly (that is ,the way I intended), but I think this uncovers a possible design flaw in the `get_transform` scheme...  

What's happening is that because there's a direct transfrom from ICRS->FK5, `get_transform` is returning that transform, _not_ a `CompositeTransform`, as it would if there were two or more steps.  `CompositeTransform` is what does the magic of making sure the intermediate frames are all of the correct type, and that's not happening here because a `CompositeTransform` is never created.

So there's two solutions I see:
1. Just say that transform functions can only rely on the "to" frames having the appropriate frame attributes, but not be of the approptiate class.  It's pretty trivial to fix the existing transforms to make that work, as the relevant methods are all static/class methods.  But it's a subtlety that may trip up user-created transforms...
2. adjust `get_transform` to always give `CompositeTransform`s, even in the one-hop or self-hop case.  That should then ensure the correct frame is always passed into the actual transforms. 

I'm slightly in favor of 1 simply because it's easier/faster to implement, and also because we can always go 1->2 later if 1 turns out confusing, while the opposite is not true.  But I'm open to your opinion here, @taldcroft , as you're probably the only other person who's looked at this enough to have one...

**Comment by taldcroft** [comment]
@eteq - to be honest I haven't looked much into the transform code itself.  I'm OK with 1 for the reasons you stated, but I'm curious why 2 isn't easier.  Isn't a single hop just a trivial case of a multi-step transform, so that at the end of `get_transform` you could always wrap a single-step or self transform into a `CompositeTransform`.  This _seems_ cleaner and has no apparent downsides, and in theory would allow the current `SkyCoord.transform_to()` to work.  But like I said I haven't had time to dig into the transform machinery, so I'll basically delegate the guts of `SkyCoord.transform_to()` to you.

**Comment by eteq** [comment]
@taldcroft - Ok, I'll go with 2, then: I have a hard time telling what "clearer" at this point because I only have my own perspective (which was the _source_ of the code).  Will implement that shortly.

**Comment by eteq** [comment]
@taldcroft - see 9dd9d35720938018faad8924c105e6a4daba57cc on eteq/astropy:coordinates-ape5 - when I rebased your branch on that, the test in question now passes

**Comment by eteq** [comment]
(well, other parts of it fail, but the particular step you mentioned here is now fine)

**Comment by taldcroft** [comment]
@eteq - stuck again on an issue related to `GenericFrame`:

```
In [10]: sc = SkyCoord('fk5', 1, 2, unit='deg', equinox='J1975', obstime='J1975')

In [12]: sc.transform_to(FK5(equinox='J1980'))
ERROR: ValueError: Coordinate attribute 'equinox'=<Time object: scale='utc' format='jyear_str' value=J1975.000> conflicts with keyword argument 'equinox'=<Time object: scale='utc' format='jyear_str' value=J1980.000> [astropy.coordinates.sky_coordinate]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-12-894f8fb563f8> in <module>()
----> 1 sc.transform_to(FK5(equinox='J1980'))

/Users/aldcroft/git/astropy/astropy/coordinates/sky_coordinate.pyc in transform_to(self, frame)
    203         # We could remove overlaps here, but the init code is set up to accept
    204         # overlaps as long as the values are identical (which they must be).
--> 205         return SkyCoord(new_coord, **frame_kwargs)
    206 
    207     def __getattr__(self, attr):

ipdb> frame_kwargs
{u'equinox': <Time object: scale='utc' format='jyear_str' value=J1980.000>, u'obstime': 'J1975'}
ipdb> generic_frame
<GenericFrame Frame: equinox=J1980.000, obstime=J1975>
ipdb> trans
<astropy.coordinates.transformations.CompositeTransform object at 0x106b47710>
ipdb> self._coord
<FK5 Coordinate: equinox=J1975.000, ra=1.0 deg, dec=2.0 deg>
ipdb> new_coord
<FK5 Coordinate: equinox=J1975.000, ra=1.0 deg, dec=2.0 deg>
```

The immediate failure in the `SkyCoord()` statement is that `new_coord` has equinox=J1975.0 from the original while the `frame_kwargs` indicate `J1980` as desired from the transform.

You can see that the `generic_frame` is correctly set with `J1980` for equinox, but the `new_coord` that got generated with `new_coord = trans(self._coord, generic_frame)` doesn't have that equinox.

I'm going to push up my latest version (which got rebased again) in a second.  This includes a new test `test_round_tripping` which brought up this problem.  Otherwise the tests in `test_sky_coord` are passing.  I haven't had time to update the `test_api_ape5` version.

**Comment by eteq** [comment]
I think I figured this out, but it'll be easier to merge and adjust this on `coordinates-ape5`, so I'll do that.  Thanks @taldcroft !

**Pull request merged**
