### PR TITLE
added lookup_name to frames

### PR DESCRIPTION
**Pull request by eteq**
This adds a way for frame objects to figure out what their aliases are in a particular transform graph.  This was triggered by discussion in astropy/astropy#2422 with @taldcroft about how to make frames visible on `SkyCoord`.

The plan there was to just add `name` property to the frame classes.  The problem with that is this: these names (or perhaps "aliases") are _not_ unique to the class.  They instead are unique to the _transform graph_.  The idea is that this might allow similar frames to be used with different names in different contexts (e.g., you might want FK5 to just be 'fk5' in the current coordinates framework, but in gWCS, it might be better named something like 'fk5_spatial_coordinate' or whatever).  But that's impossible if you force the "short" name to live on the class itself.  

So this PR is a modification of that idea to instead add a `lookup_name` class method.  For `SkyCoord`, this just means where originally we had been thinking `self.frame.name`, after this PR it could be `self.frame.lookup_name(frame_transform_graph)`.  Let me know what you think, @taldcroft.

### CODE REVIEW

**Comment by taldcroft** [comment]
Is being able to make different transform paths the driving use case for being able to assign different names for the same frame in different transformation graphs?  I.e. is the alias name what gets used to find the transform function? 

Anyway, the main point is that `SkyCoord` only knows about the master transform graph.  So can we have a property like `master_name` that is convenient to use?  Otherwise I'll probably end up writing a convenience function like `def name(x): return x.lookup_name(master_transform_graph)` and using that, which would sortof defeat the purpose of this PR.

**Comment by taldcroft** [comment]
Or maybe have the `frame_transform_graph` default to `master_transform_graph`.  I would still like to use it like a property semantically so that `name` instead of `lookup_name` would make sense, i.e. `if skycoord.frame.name() == 'icrs': print 'yay!'`.

**Comment by eteq** [comment]
@taldcroft :

> Is being able to make different transform paths the driving use case for being able to assign different names for the same frame in different transformation graphs? I.e. is the alias name what gets used to find the transform function?

Not quite: it's that different instances of `TransformGraph` can use different aliases for the same frame class.  The transforms themselves have no special names (aside from the names of the functions implementing them).

I'm not sure I understand your second comment, though.  There is _no_ `master_transform_graph` now.  `frame_transform_graph` is sort of analogous, but it lives in `builtin_frames`, and is restricted to the domain of spatial/celestial coordinates.  The idea is that the `TransformGraph` machinery will be used by _other_ `TransformGraph`  instances for various pieces of gWCS.  So that's why `master_transform_graph` was removed - to remove the global state that was previously inherent in `TransformGraph`.

But `SkyCoord` is already (and by design) tied to the spatial coordinate stuff.  So using `builtin_frames.frame_transform_graph` makes sense in that context (we're of course already doing it to do the transforms themselves). So I like your idea of something like `master_name` (I'd prefer `frame_name`?) as a property on `SkyCoord`. I'll add that to this PR in a bit.

**Comment by taldcroft** [comment]
> Not quite: it's that different instances of TransformGraph can use different aliases for the same frame class. The transforms themselves have no special names (aside from the names of the functions implementing them).

I guess my question was why you _need_ different aliases for the same frame class.

**Comment by taldcroft** [comment]
Sorry, I did mean `frame_transform_graph`, which is (as you say) effectively the global transform graph for spatial coordinates and `SkyCoord`.

The question about why you _need_ different aliases is wondering why you cannot have the frame name be hardwired for a particular frame class.  The only reason I could think of is if the transformation function(s) are dynamically located using the frame name in the transform graph.  That would be one mechanism to allow for different transforms for the same frame class.

**Comment by eteq** [comment]
@taldcroft - I've implemented `frame_name` now.

> I guess my question was why you need different aliases for the same frame class.

It depends on what "need" means.  It _could_ be implemented that way (it's a non-trivial but doable change in `transformations.py`), but that then requires all future `TransformGraphs` use the same alias convention.  So mainly what I'm thinking of is my example from above: with gWCS it's quite possible that some of the frames defined here will also be in a different `TransformGraph` that follows different naming conventions.  For example, a transform graph appropriate to WCS for data cubes might have lots of different wavelength frames _and_ the spatial coordinates we're talking about here.  So then it might make sense for the names to be "fk5_spatial", "icrs_spatial", "wavelength", "frequency_optical", etc.  But if there's one and only one alias that we impose now, that option is no longer available.

It may be less obvious why that's useful right now because "icrs", "fk5", et al. are pretty unambiguous.  But once we have the whole IAU2000 stack implemented, more will show up, like "itrs", "tirs", "cirs", "gcrs", and more, and the chances of name collisions when you put that in a gWCS framework goes up pretty quickly. 

> That would be one mechanism to allow for different transforms for the same frame class.

I'm not sure what you mean by this?  Right now that' managed by having different transformation objects. We _could_ associate names with the transformation, I suppose, but that's distinct from associating names with the _frames_.  And it doesn't seem that useful to me because it just introduces more complication.  Personally, even for the frames I see the names as a "necessary evil" - I would have preferred no names at all and just use the frame classes, but there was resistance to that in APE5.

**Comment by eteq** [comment]
@taldcroft - At any rate, will the current `frame_name` work for you to implement `SkyCoord.frame`?  

Also, there's an alternative approach for you that has occurred to me: you can just do `frame_transform_graph.lookup_name(self.frame)` anywhere you need the frame name.  That should yield the same thing the same thing as this (although the `frame_name` in this PR is quite less efficient because it has to search through the graph).  

I'm now realizing that was the whole point of implementing `TransformGraph.lookup_name` the way it is was to allow use in this way... But if you think it's important for `frame_name` to be part of the public API, that's ok too.

**Comment by taldcroft** [comment]
OK, looks good.

**Comment by taldcroft** [comment]
I'll work on changing the frame attribute tomorrow so you can go ahead and merge this.

**Comment by eteq** [comment]
Alright, cool, merging now, then, @taldcroft.

**Comment by taldcroft** [comment]
I'm getting even more confused now that I see the same frame class can appear in the transform graph under two different names.  Brain exploding...

> It depends on what "need" means. It could be implemented that way (it's a non-trivial but doable change in transformations.py), but that then requires all future TransformGraphs use the same alias convention. So mainly what I'm thinking of is my example from above: with gWCS it's quite possible that some of the frames defined here will also be in a different TransformGraph that follows different naming conventions. For example, a transform graph appropriate to WCS for data cubes might have lots of different wavelength frames and the spatial coordinates we're talking about here. So then it might make sense for the names to be "fk5_spatial", "icrs_spatial", "wavelength", "frequency_optical", etc. But if there's one and only one alias that we impose now, that option is no longer available.

In your original concept and current implementation, the frame alias names are just second-class entities, essentially tagging along for the ride.  At least that's what I understand from what you've explained.   If we _never had names at all_ (your preference) then there would exactly one and only one way to refer to a frame, i.e. `FK5` or `ICRS` or any of the other IAU2000 stack frames.  So why shouldn't the frame alias be similarly unique?  What would people do if they really want `FK5_Spatial`?  Probably subclass `class FK5_Spatial(FK5): pass`.   So imagine:

```
class FK5(BaseCoordinateFrame):
    _name = 'fk5'
...

class FK5_Spatial(FK5):
    _name = 'fk5_spatial'
```

Now the question is: _What limitation does this scheme imply?_  What become impossible or cumbersome in this way that would not have the same issue if there were only frame classes.

**Comment by eteq** [comment]
@taldcroft - what you say here makes sense, and I couldn't really come up with an answer to 

> What limitation does this scheme imply?

So in #30 I re-implemented this is a `name` class attribute on the frames

**Pull request merged**
