### PR TITLE
Validate time inputs and allow any value that Time accepts

### PR DESCRIPTION
**Pull request by taldcroft**

### CODE REVIEW

**Comment by eteq** [comment]
@taldcroft - This is definitely a good thing to do, but before I merge this, there's a question of whether or not this is right _place_ to do this checking.  That is, this now means anything in `TIME_FRAME_ATTRS` gets time validation, but nothing else does, _and_ user coordinates cannot make use of this validation (because it's hard-coded in `baseframe.py`).

So I had been thinking of implementing validation of this sort in the `__init__` of each individual frame object, and to maintain that idiom for other frame attributes (do all validation in the frame's `__init__`).  Of course, we still want your tests here to pass, and `_convert_to_time` is needed, but before I make those modifications, I wanted to make sure that sounds reasonable to you.

**Comment by taldcroft** [comment]
In your plan if you make a custom frame then you need to explicitly remember to do the conversion / validation in the `__init__` for `obstime` and `equinox` attributes, while in this PR it happens automatically (at least for known time attributes).  I was just trying to avoid the problem of boilerplate code for user classes which was a concern for the original coordinates implementation.

But what you said will work, no problem.

**Comment by eteq** [comment]
@taldcroft - Ah, I see your point... perhaps the thing to do is to just change it so that `TIME_FRAME_ATTRS` is a class-level attribute (like `preferred_attr_names` et al.), but still with `obstime` and `equinox` as defaults ?

**Comment by taldcroft** [comment]
That makes sense and I was just thinking something like that might work.

**Comment by eteq** [comment]
Ok, cool.  Are you going to do that, or should I merge and then do it myself in `coordinates-ape5`?

**Comment by taldcroft** [comment]
Why don't you merge and then fix it in coordinates-ape5.

**Comment by eteq** [comment]
Ok, will do.

**Comment by eteq** [comment]
alright, done: 65edb13675f8220d0d00b001857e958c69c96355

**Pull request merged**
